# syntax=docker/dockerfile:1
ARG RUBY_VERSION=3.2.2
ARG BUNDLE_VERSION=2.4.12

FROM ruby:${RUBY_VERSION}

ARG BUNDLE_VERSION
ENV BUNDLE_VERSION ${BUNDLE_VERSION}

RUN apt-get update -qq
RUN apt-get install -y build-essential nodejs

RUN gem install bundler -v ${BUNDLE_VERSION}

ENV SRC /src
RUN mkdir $SRC
WORKDIR $SRC

ENV BUNDLE_PATH $SRC/vendor/bundle

ADD . $SRC
